#version 430

layout (local_size_x = 16, local_size_y = 16) in;

layout (rgba8, binding = 0) uniform image2D img_output;

uniform float uTime;

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID);

    float value;
    if (((gl_WorkGroupID.x & 1u) != 1u) != ((gl_WorkGroupID.y & 1u) == 1u)) {
        value = cos(uTime)*0.5 + 0.5;
    } else {
        value = sin(uTime)*0.5 + 0.5;
    }

    vec4 pixel = vec4(value, value, value, 1.0);
    imageStore(img_output, coords, pixel);
}